; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

; Velocidade do monitor serial (deve bater com SERIAL_BAUD_RATE no Config.h)
monitor_speed = 115200

; Velocidade de upload para o D1 Mini
upload_speed = 921600

; Bibliotecas externas
lib_deps =
	bblanchon/ArduinoJson@^6.21.5
